### ISSUE TITLE
post 'spring-webflux-cache' excerpt 

### ISSUE THREAD

**Issue by phantasmicmeans** [naver-media-tech/naver-media-tech.github.io#6]
@dreamchaser3 유정님!

현재 본문 발췌 요약본 스펙이 포스트의 첫 문단을 기준으로 이뤄지고 있습니다.
포스트 본문에서 아래 개요, br 부분 삭제 가능하실지 검토 부탁드릴게요 :)

이부분도 가이드에 추가 되어야겠네요.. 

```
# 개요
--------------
<br>

스프링 웹플럭스와 Reactor를 사용하여 웹서버를 개발할 때 고민이 되는 부분이 있습니다.
....
```

### AS-IS
![image](https://user-images.githubusercontent.com/20153890/90952423-65aca380-e49e-11ea-8595-18b36c2a6627.png)

### TO-BE (삭제 후)
![image](https://user-images.githubusercontent.com/20153890/90952512-15821100-e49f-11ea-8cb1-a0cb6831d46f.png)

홈 노출 테스트는 `staging: false` 주고 하시면 됩니다. 

(추가로 이미지도 여백이 조금 적으면 좋을 것 같긴 하네요..ㅎㅎ 이미지 노출 사이즈는 100x70 고정입니다. )

**Comment by dreamchaser3** [comment]
@phantasmicmeans 

확인 감사합니다~ 👍 
수정할게요~

**Comment by phantasmicmeans** [comment]
댓글테스트
